/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongRouteImport } from './routes/wrong'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as FrqRouteImport } from './routes/frq'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MockIndexRouteImport } from './routes/mock.index'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as MockRandomRouteImport } from './routes/mock.random'
import { Route as MockSlugRouteImport } from './routes/mock.$slug'
import { Route as ApiFeedbackRouteImport } from './routes/api/feedback'
import { Route as ApiAiExplainRouteImport } from './routes/api/ai-explain'
import { Route as ApiFrqUploadRouteImport } from './routes/api/frq/upload'
import { Route as ApiFrqGradeRouteImport } from './routes/api/frq/grade'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminUploadImageRouteImport } from './routes/api/admin/upload-image'
import { Route as ApiAdminReanalyzeRouteImport } from './routes/api/admin/reanalyze'
import { Route as ApiAdminQuestionsRouteImport } from './routes/api/admin/questions'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminImportRouteImport } from './routes/api/admin/import'
import { Route as ApiAdminFrqsRouteImport } from './routes/api/admin/frqs'
import { Route as ApiAdminFeedbackRouteImport } from './routes/api/admin/feedback'
import { Route as ApiAdminAuditRouteImport } from './routes/api/admin/audit'

const WrongRoute = WrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FrqRoute = FrqRouteImport.update({
  id: '/frq',
  path: '/frq',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MockIndexRoute = MockIndexRouteImport.update({
  id: '/mock/',
  path: '/mock/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRandomRoute = MockRandomRouteImport.update({
  id: '/mock/random',
  path: '/mock/random',
  getParentRoute: () => rootRouteImport,
} as any)
const MockSlugRoute = MockSlugRouteImport.update({
  id: '/mock/$slug',
  path: '/mock/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFeedbackRoute = ApiFeedbackRouteImport.update({
  id: '/api/feedback',
  path: '/api/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExplainRoute = ApiAiExplainRouteImport.update({
  id: '/api/ai-explain',
  path: '/api/ai-explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrqUploadRoute = ApiFrqUploadRouteImport.update({
  id: '/api/frq/upload',
  path: '/api/frq/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFrqGradeRoute = ApiFrqGradeRouteImport.update({
  id: '/api/frq/grade',
  path: '/api/frq/grade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadImageRoute = ApiAdminUploadImageRouteImport.update({
  id: '/api/admin/upload-image',
  path: '/api/admin/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReanalyzeRoute = ApiAdminReanalyzeRouteImport.update({
  id: '/api/admin/reanalyze',
  path: '/api/admin/reanalyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuestionsRoute = ApiAdminQuestionsRouteImport.update({
  id: '/api/admin/questions',
  path: '/api/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportRoute = ApiAdminImportRouteImport.update({
  id: '/api/admin/import',
  path: '/api/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFrqsRoute = ApiAdminFrqsRouteImport.update({
  id: '/api/admin/frqs',
  path: '/api/admin/frqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminFeedbackRoute = ApiAdminFeedbackRouteImport.update({
  id: '/api/admin/feedback',
  path: '/api/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditRoute = ApiAdminAuditRouteImport.update({
  id: '/api/admin/audit',
  path: '/api/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/frq': typeof FrqRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/mock/$slug': typeof MockSlugRoute
  '/mock/random': typeof MockRandomRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/mock/': typeof MockIndexRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/frqs': typeof ApiAdminFrqsRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/frq/grade': typeof ApiFrqGradeRoute
  '/api/frq/upload': typeof ApiFrqUploadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/frq': typeof FrqRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/mock/$slug': typeof MockSlugRoute
  '/mock/random': typeof MockRandomRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/mock': typeof MockIndexRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/frqs': typeof ApiAdminFrqsRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/frq/grade': typeof ApiFrqGradeRoute
  '/api/frq/upload': typeof ApiFrqUploadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/frq': typeof FrqRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/api/feedback': typeof ApiFeedbackRoute
  '/mock/$slug': typeof MockSlugRoute
  '/mock/random': typeof MockRandomRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/mock/': typeof MockIndexRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/feedback': typeof ApiAdminFeedbackRoute
  '/api/admin/frqs': typeof ApiAdminFrqsRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/frq/grade': typeof ApiFrqGradeRoute
  '/api/frq/upload': typeof ApiFrqUploadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/frq'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/api/feedback'
    | '/mock/$slug'
    | '/mock/random'
    | '/practice/$slug'
    | '/mock/'
    | '/api/admin/audit'
    | '/api/admin/feedback'
    | '/api/admin/frqs'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
    | '/api/admin/users'
    | '/api/frq/grade'
    | '/api/frq/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/frq'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/api/feedback'
    | '/mock/$slug'
    | '/mock/random'
    | '/practice/$slug'
    | '/mock'
    | '/api/admin/audit'
    | '/api/admin/feedback'
    | '/api/admin/frqs'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
    | '/api/admin/users'
    | '/api/frq/grade'
    | '/api/frq/upload'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/frq'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/api/feedback'
    | '/mock/$slug'
    | '/mock/random'
    | '/practice/$slug'
    | '/mock/'
    | '/api/admin/audit'
    | '/api/admin/feedback'
    | '/api/admin/frqs'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
    | '/api/admin/users'
    | '/api/frq/grade'
    | '/api/frq/upload'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  FrqRoute: typeof FrqRoute
  TermsRoute: typeof TermsRoute
  WrongRoute: typeof WrongRoute
  ApiAiExplainRoute: typeof ApiAiExplainRoute
  ApiFeedbackRoute: typeof ApiFeedbackRoute
  MockSlugRoute: typeof MockSlugRoute
  MockRandomRoute: typeof MockRandomRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  MockIndexRoute: typeof MockIndexRoute
  ApiAdminAuditRoute: typeof ApiAdminAuditRoute
  ApiAdminFeedbackRoute: typeof ApiAdminFeedbackRoute
  ApiAdminFrqsRoute: typeof ApiAdminFrqsRoute
  ApiAdminImportRoute: typeof ApiAdminImportRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminQuestionsRoute: typeof ApiAdminQuestionsRoute
  ApiAdminReanalyzeRoute: typeof ApiAdminReanalyzeRoute
  ApiAdminUploadImageRoute: typeof ApiAdminUploadImageRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiFrqGradeRoute: typeof ApiFrqGradeRoute
  ApiFrqUploadRoute: typeof ApiFrqUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong': {
      id: '/wrong'
      path: '/wrong'
      fullPath: '/wrong'
      preLoaderRoute: typeof WrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frq': {
      id: '/frq'
      path: '/frq'
      fullPath: '/frq'
      preLoaderRoute: typeof FrqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/': {
      id: '/mock/'
      path: '/mock'
      fullPath: '/mock/'
      preLoaderRoute: typeof MockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/random': {
      id: '/mock/random'
      path: '/mock/random'
      fullPath: '/mock/random'
      preLoaderRoute: typeof MockRandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock/$slug': {
      id: '/mock/$slug'
      path: '/mock/$slug'
      fullPath: '/mock/$slug'
      preLoaderRoute: typeof MockSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/feedback': {
      id: '/api/feedback'
      path: '/api/feedback'
      fullPath: '/api/feedback'
      preLoaderRoute: typeof ApiFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-explain': {
      id: '/api/ai-explain'
      path: '/api/ai-explain'
      fullPath: '/api/ai-explain'
      preLoaderRoute: typeof ApiAiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frq/upload': {
      id: '/api/frq/upload'
      path: '/api/frq/upload'
      fullPath: '/api/frq/upload'
      preLoaderRoute: typeof ApiFrqUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/frq/grade': {
      id: '/api/frq/grade'
      path: '/api/frq/grade'
      fullPath: '/api/frq/grade'
      preLoaderRoute: typeof ApiFrqGradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-image': {
      id: '/api/admin/upload-image'
      path: '/api/admin/upload-image'
      fullPath: '/api/admin/upload-image'
      preLoaderRoute: typeof ApiAdminUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reanalyze': {
      id: '/api/admin/reanalyze'
      path: '/api/admin/reanalyze'
      fullPath: '/api/admin/reanalyze'
      preLoaderRoute: typeof ApiAdminReanalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/questions': {
      id: '/api/admin/questions'
      path: '/api/admin/questions'
      fullPath: '/api/admin/questions'
      preLoaderRoute: typeof ApiAdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import': {
      id: '/api/admin/import'
      path: '/api/admin/import'
      fullPath: '/api/admin/import'
      preLoaderRoute: typeof ApiAdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/frqs': {
      id: '/api/admin/frqs'
      path: '/api/admin/frqs'
      fullPath: '/api/admin/frqs'
      preLoaderRoute: typeof ApiAdminFrqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/feedback': {
      id: '/api/admin/feedback'
      path: '/api/admin/feedback'
      fullPath: '/api/admin/feedback'
      preLoaderRoute: typeof ApiAdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit': {
      id: '/api/admin/audit'
      path: '/api/admin/audit'
      fullPath: '/api/admin/audit'
      preLoaderRoute: typeof ApiAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  FrqRoute: FrqRoute,
  TermsRoute: TermsRoute,
  WrongRoute: WrongRoute,
  ApiAiExplainRoute: ApiAiExplainRoute,
  ApiFeedbackRoute: ApiFeedbackRoute,
  MockSlugRoute: MockSlugRoute,
  MockRandomRoute: MockRandomRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  MockIndexRoute: MockIndexRoute,
  ApiAdminAuditRoute: ApiAdminAuditRoute,
  ApiAdminFeedbackRoute: ApiAdminFeedbackRoute,
  ApiAdminFrqsRoute: ApiAdminFrqsRoute,
  ApiAdminImportRoute: ApiAdminImportRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminQuestionsRoute: ApiAdminQuestionsRoute,
  ApiAdminReanalyzeRoute: ApiAdminReanalyzeRoute,
  ApiAdminUploadImageRoute: ApiAdminUploadImageRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiFrqGradeRoute: ApiFrqGradeRoute,
  ApiFrqUploadRoute: ApiFrqUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
