/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongRouteImport } from './routes/wrong'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as MockRouteImport } from './routes/mock'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PracticeSlugRouteImport } from './routes/practice.$slug'
import { Route as ApiAiExplainRouteImport } from './routes/api/ai-explain'
import { Route as ApiAdminUploadImageRouteImport } from './routes/api/admin/upload-image'
import { Route as ApiAdminReanalyzeRouteImport } from './routes/api/admin/reanalyze'
import { Route as ApiAdminQuestionsRouteImport } from './routes/api/admin/questions'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminImportRouteImport } from './routes/api/admin/import'
import { Route as ApiAdminAuditRouteImport } from './routes/api/admin/audit'

const WrongRoute = WrongRouteImport.update({
  id: '/wrong',
  path: '/wrong',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const MockRoute = MockRouteImport.update({
  id: '/mock',
  path: '/mock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSlugRoute = PracticeSlugRouteImport.update({
  id: '/practice/$slug',
  path: '/practice/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExplainRoute = ApiAiExplainRouteImport.update({
  id: '/api/ai-explain',
  path: '/api/ai-explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadImageRoute = ApiAdminUploadImageRouteImport.update({
  id: '/api/admin/upload-image',
  path: '/api/admin/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminReanalyzeRoute = ApiAdminReanalyzeRouteImport.update({
  id: '/api/admin/reanalyze',
  path: '/api/admin/reanalyze',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuestionsRoute = ApiAdminQuestionsRouteImport.update({
  id: '/api/admin/questions',
  path: '/api/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImportRoute = ApiAdminImportRouteImport.update({
  id: '/api/admin/import',
  path: '/api/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuditRoute = ApiAdminAuditRouteImport.update({
  id: '/api/admin/audit',
  path: '/api/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mock': typeof MockRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mock': typeof MockRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/mock': typeof MockRoute
  '/terms': typeof TermsRoute
  '/wrong': typeof WrongRoute
  '/api/ai-explain': typeof ApiAiExplainRoute
  '/practice/$slug': typeof PracticeSlugRoute
  '/api/admin/audit': typeof ApiAdminAuditRoute
  '/api/admin/import': typeof ApiAdminImportRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/questions': typeof ApiAdminQuestionsRoute
  '/api/admin/reanalyze': typeof ApiAdminReanalyzeRoute
  '/api/admin/upload-image': typeof ApiAdminUploadImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/mock'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/practice/$slug'
    | '/api/admin/audit'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/mock'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/practice/$slug'
    | '/api/admin/audit'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/mock'
    | '/terms'
    | '/wrong'
    | '/api/ai-explain'
    | '/practice/$slug'
    | '/api/admin/audit'
    | '/api/admin/import'
    | '/api/admin/login'
    | '/api/admin/questions'
    | '/api/admin/reanalyze'
    | '/api/admin/upload-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MockRoute: typeof MockRoute
  TermsRoute: typeof TermsRoute
  WrongRoute: typeof WrongRoute
  ApiAiExplainRoute: typeof ApiAiExplainRoute
  PracticeSlugRoute: typeof PracticeSlugRoute
  ApiAdminAuditRoute: typeof ApiAdminAuditRoute
  ApiAdminImportRoute: typeof ApiAdminImportRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminQuestionsRoute: typeof ApiAdminQuestionsRoute
  ApiAdminReanalyzeRoute: typeof ApiAdminReanalyzeRoute
  ApiAdminUploadImageRoute: typeof ApiAdminUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong': {
      id: '/wrong'
      path: '/wrong'
      fullPath: '/wrong'
      preLoaderRoute: typeof WrongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock': {
      id: '/mock'
      path: '/mock'
      fullPath: '/mock'
      preLoaderRoute: typeof MockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$slug': {
      id: '/practice/$slug'
      path: '/practice/$slug'
      fullPath: '/practice/$slug'
      preLoaderRoute: typeof PracticeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-explain': {
      id: '/api/ai-explain'
      path: '/api/ai-explain'
      fullPath: '/api/ai-explain'
      preLoaderRoute: typeof ApiAiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload-image': {
      id: '/api/admin/upload-image'
      path: '/api/admin/upload-image'
      fullPath: '/api/admin/upload-image'
      preLoaderRoute: typeof ApiAdminUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reanalyze': {
      id: '/api/admin/reanalyze'
      path: '/api/admin/reanalyze'
      fullPath: '/api/admin/reanalyze'
      preLoaderRoute: typeof ApiAdminReanalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/questions': {
      id: '/api/admin/questions'
      path: '/api/admin/questions'
      fullPath: '/api/admin/questions'
      preLoaderRoute: typeof ApiAdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import': {
      id: '/api/admin/import'
      path: '/api/admin/import'
      fullPath: '/api/admin/import'
      preLoaderRoute: typeof ApiAdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/audit': {
      id: '/api/admin/audit'
      path: '/api/admin/audit'
      fullPath: '/api/admin/audit'
      preLoaderRoute: typeof ApiAdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MockRoute: MockRoute,
  TermsRoute: TermsRoute,
  WrongRoute: WrongRoute,
  ApiAiExplainRoute: ApiAiExplainRoute,
  PracticeSlugRoute: PracticeSlugRoute,
  ApiAdminAuditRoute: ApiAdminAuditRoute,
  ApiAdminImportRoute: ApiAdminImportRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminQuestionsRoute: ApiAdminQuestionsRoute,
  ApiAdminReanalyzeRoute: ApiAdminReanalyzeRoute,
  ApiAdminUploadImageRoute: ApiAdminUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
